//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vHotelier
    {
        public decimal id { get; set; }
        public string mail { get; set; }
        public string motdepasse { get; set; }
        public string nom { get; set; }
        public decimal idPays { get; set; }
        public string etat { get; set; }
        public string ville { get; set; }
        public string codePostal { get; set; }
        public string adrLigne2 { get; set; }
        public string adrLigne1 { get; set; }
        public string prenom { get; set; }
    }
}
